name: dql
channels:
- pytorch
- defaults
dependencies:
- cuda90
- cudnn
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pip
- python
- pytorch
- torchvision
- tqdm
- tensorboard
- tensorflow
- pip:
  - atari-py
  - git+https://github.com/openai/gym/
  - tensorboardX==1.5
  - pytest
  - moviepy
  - imageio